platform :ios, '7.0'
inhibit_all_warnings!


    target 'MG_PrizeClaw' do
        inherit! :search_paths
        pod 'AFNetworking', '~> 3.0'
        pod 'SDAutoLayout', '~> 2.2.0'
        pod 'Masonry'
        pod 'MJRefresh'
        pod 'SDWebImage'
        pod 'MBProgressHUD'
        pod 'AMapLocation'
        pod 'AMapNavi'
end
